/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class EncryptedDeviceKeyPair {
  constructor(wrappingKey: Buffer, encryptionKeyCiphertext: Buffer, encryptionKeyNonce: Buffer, decryptionKeyCiphertext: Buffer, decryptionKeyNonce: Buffer)
  get wrappingKey(): Buffer
  get encryptionKeyCiphertext(): Buffer
  get encryptionKeyNonce(): Buffer
  get decryptionKeyCiphertext(): Buffer
  get decryptionKeyNonce(): Buffer
}

export declare class EncryptedPassword {
  constructor(argon2Salt: Buffer, hkdfSalt: Buffer, kemNonce: Buffer, kemCiphertext: Buffer, passwordNonce: Buffer, passwordCiphertext: Buffer)
  get argon2Salt(): Buffer
  get hkdfSalt(): Buffer
  get kemNonce(): Buffer
  get kemCiphertext(): Buffer
  get passwordNonce(): Buffer
  get passwordCiphertext(): Buffer
}

export declare class EncryptedVaultKey {
  constructor(argon2Salt: Buffer, vaultKeyCiphertext: Buffer, vaultKeyNonce: Buffer)
  get argon2Salt(): Buffer
  get vaultKeyCiphertext(): Buffer
  get vaultKeyNonce(): Buffer
}

export declare class KeyPair {
  constructor(encryptionKey: Buffer, decryptionKey: Buffer)
  get encryptionKey(): Buffer
  get decryptionKey(): Buffer
}

export declare function decryptDeviceKeys(wrappingKey: Uint8Array, keyCiphertext: Uint8Array, keyNonce: Uint8Array): Buffer

export declare function decryptNetworkPacket(encryptedData: Uint8Array, sharedSecretKey: Uint8Array): string

export declare function decryptPassword(masterPassword: Uint8Array, kemPrivateKey: Uint8Array, encryptedData: EncryptedPassword): Buffer

export declare function decryptVaultKey(masterPassword: Uint8Array, encryptedVaultKey: EncryptedVaultKey): Buffer

export declare function encryptNetworkPacket(data: string, sharedSecretKey: Uint8Array): Buffer

export declare function encryptPassword(masterPassword: Uint8Array, encryptionKey: Uint8Array, actualPassword: Uint8Array): EncryptedPassword

export declare function generateEncryptedDeviceKeys(): EncryptedDeviceKeyPair

export declare function generateEncryptedVaultKey(masterPassword: Uint8Array): EncryptedVaultKey

export declare function generateNetworkSharedSecretKey(): Buffer

export declare function generatePassword(options?: PasswordGeneratorOptions | undefined | null): string

export declare function keygen(): KeyPair

export interface PasswordGeneratorOptions {
  length?: number
  includeNumbers?: boolean
  includeUppercase?: boolean
  includeLowercase?: boolean
  includeSymbols?: boolean
  minNumbers?: number
  minUppercase?: number
  minLowercase?: number
  minSymbols?: number
}
